FROM golang:1.14

RUN apk update
RUN apk add --no-cache ruby vim \
    flex bison  \
    libc-dev \
    bash              \
    build-base        \
    coreutils         \
    gcc               \
    git               \
    make              \
    musl-dev          \
    openssl-dev       \
    rpm               \
    tree              \
    lz4-dev           \
    zlib-dev          \
    zstd-dev          \
    librdkafka-dev    \
    libpcap-dev       \
    pkgconf           \
    wget

RUN apt-get install flex bison -y
RUN wget http://www.tcpdump.org/release/libpcap-1.8.1.tar.gz && tar xzf libpcap-1.8.1.tar.gz && cd libpcap-1.8.1 && ./configure && make install
RUN apt-get install default-jre default-jdk -y
RUN go get github.com/google/gopacket
RUN go get -u golang.org/x/lint/golint

WORKDIR /go/src/github.com/buger/goreplay/
ADD . /go/src/github.com/buger/goreplay/
RUN go get
