FROM golang:alpine

RUN apk update
RUN apk add --no-cache ruby vim \
    flex bison  \
    libc-dev \
    bash              \
    build-base        \
    coreutils         \
    gcc               \
    git               \
    make              \
    musl-dev          \
    openssl-dev       \
    rpm               \
    tree              \
    lz4-dev           \
    zlib-dev          \
    zstd-dev          \
    librdkafka-dev    \
    libpcap-dev       \
    pkgconf           \
    wget

RUN go get github.com/google/gopacket
RUN go get -u golang.org/x/lint/golint

WORKDIR /go/src/github.com/buger/goreplay/
ADD . /go/src/github.com/buger/goreplay/
RUN go get
